### ISSUE TITLE
Wrong results with a different data

### ISSUE THREAD

**Issue by devisdevis** [adrHuerta/rainfall_onset#2]
Dear @adrHuerta,
This is actually a good job and I found it interesting, especially the presentation of results.
When I use the functions with a different dataset it gives suspicious results and "NaN"s (see the screenshot).

![Screenshot_2022-02-24_19-57-34](https://user-images.githubusercontent.com/20596326/155597989-05a640d9-9f0a-4eb4-9757-45b8cc005266.png).

Any idea what could cause that? 
Attached is the sample data.
Thanks.

[test.csv](https://github.com/adrHuerta/rainfall_onset/files/8135407/test.csv)

**Comment by adrHuerta** [comment]
Dear @devisdevis this is interesting, I will check it!
But, please let me know a little bit of the metadata (as location, lat lon and elevation information) of the time series

**Comment by devisdevis** [comment]
Dear @adrHuerta ,
Find details on the location of the station
latitude = 9.550
longitude = 1.167
elevation = 341m

**Comment by adrHuerta** [comment]
Dear @devisdevis 

Sorry for my late reply!
I finally found the issue; your time series does not have the same seasonality as the time series from the example.
If you check line number 30 of rainfall_onset_functions.R, you will see that I have changed the order of the dates. This is done because the wet season began in November and ended in February of the following year. However, your time series started in April and ended in October. Therefore, applying the original code to your function will appear some errors.

To solve this issue, it is only needed to make some minor changes in the functions. I did this, and I got the following:
![image](https://user-images.githubusercontent.com/25495945/160023254-5f87a7be-9ca1-4a7c-b8c4-b11ed057d144.png)

As you see, now the onset and cessation dates are adequate, and the same for the extreme indices.
I made a new script for your time series, would you let me add your time series as an example? It is quite interesting to have this different behavior.

**Comment by devisdevis** [comment]
Dear @adrHuerta,
Thank you for your feedback. I looked for the modified version of the script and could not find it. Did you add the modification to the GitHub version ? I tried modifying it without success. Could please share your script? Thank you.
Yes you can add the data as an exemple.

**Comment by adrHuerta** [comment]
Dear @devisdevis 

I have already added it, check https://github.com/adrHuerta/rainfall_onset/blob/master/example2.R
It should be working well, please note the new functions
